version: "3"
services:
  web:
    container_name: bdd_workshop_web
    image: node:18-alpine3.14
    ports:
      - '${WEB_EXTERNAL_PORT}:${WEB_PORT}'
    volumes:
      - ./:/var/www
    working_dir: /var/www
    command: sh -c "npm install && npm run build && npm run start"
    networks:
      - nw
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      WEB_HOST: web
      WEB_PORT: ${WEB_PORT}
  db:
    container_name: bdd_workshop_db
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_EXTERNAL_PORT}:3306'
    networks:
      - nw
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 2s
        retries: 10

networks:
    nw:
